### ISSUE TITLE
Ollama excluded from aspire manifest.json

### ISSUE THREAD

**Issue by MrCSharp22** [CommunityToolkit/Aspire#341]
### Describe the bug

Hi, I am using the Ollama integration as follows:

```csharp
var ollama = builder.AddOllama("ollama")
    .WithDataVolume()
    .AddModel("phi3.5");
```

when generating the manifest.json, there is no Ollama resource in the output. Digging into the `AddOllama(..)` extension method, I found that it is calling `ExcludeFromManifest()` (https://github.com/CommunityToolkit/Aspire/blob/a49aab16aacd427663063682b840c262371fcfd7/src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs#L73) 

I am not sure I understand the reason behind this decision. I was expecting it to be included so when I use a tool like Aspir8 to get a docker-compose file, Ollama would be there as a service.

### Steps to reproduce

```text
In a new aspire project, include the following in AppHost:


var ollama = builder.AddOllama("ollama")
    .WithDataVolume()
    .AddModel("phi3.5");


run `dotnet run --publisher manifest --output-path ../aspire-manifest.json` then open the manifest file. Notice the missing Ollama resource.
```

### Expected behavior

I expect that the Ollama resource is not excluded from the manifest file.

### IDE and version

VS 2022

### IDE version

17.12.3

### Nuget packages

```text
CommunityToolkit.Aspire.Hosting.Ollama (9.1.0)
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by aaronpowell** [comment]
This is by design.

Ollama has a few things about it that makes it unsuitable for production workloads.

There is no authentication model on Ollama, meaning that anyone who has access to the HTTP endpoint execute requests against the model (chat/embedding/etc.), can download new models and push models.

Another reason that Ollama is ill-suited for production is that it doesn't have anything in place to handle concurrency, meaning that it wouldn't work well under high load, you'd be forced to scale out the container host.

For production, it's recommended you use a dedicated model hosting platform, something like Azure AI with Model-as-a-Service (which I'm experimenting with, but it's a somewhat complex thing to implement) or HuggingFace if you want a more cloud agnostic approach.

If you **really** want to deploy the Ollama container to production, and are understanding of the risks, you can override the behaviour by removing the `ManifestPublishingCallbackAnnotation` annotation from the resource's `Annotations` collection.

**Comment by MrCSharp22** [comment]
Thanks @aaronpowell that makes perfect sense. Thanks for the explanation.

However, I would suggest that, at least, the explanation should be included somewhere in the README file or the MS Docs as I don't think I saw anything about it.

If this package is available only to support local dev scenarios, can it be flagged as such?

For my use case (learning aspire and building a scrappy self-hosted app with it), Ollama would work fine.

**Comment by aaronpowell** [comment]
I'll improve the docs
