### ISSUE TITLE
NPM Package installer - if package.lock exists - use npm ci instead of npm install

### ISSUE THREAD

**Issue by erikrenaud** [CommunityToolkit/Aspire#95]
### Related to an existing integration?

Yes

### Existing integration

npm extensions - vite

### Overview

On the CI servers, i usually recommend to run npm ci instead of npm install to install node packages.

It resolves to the same tree as what is saved in the package.lock.

### Usage example

empty.

### Breaking change?

Yes

### Alternatives

Kinda - npm ci could yield different results than npm install

### Help us help you

No, just wanted to propose this

**Comment by aaronpowell** [comment]
How are you configuring your runs for CI with Aspire? I would think that it's probably best to only run the installer via Aspire when you are doing local development as in CI you're better off preparing a container for the Node app separately.

Here's a thought though - we could add a bool parameters to the function like `ciMode` and if it's true use `npm ci` rather than `npm install`, then leave it to the consumer to dictate how that is set. It would mean that we don't have to code for how different CI environments report themselves, and gives more flexibility (you could even opt-in locally if desired).

**Comment by erikrenaud** [comment]
> How are you configuring your runs for CI with Aspire? I would think that it's probably best to only run the installer via Aspire when you are doing local development as in CI you're better off preparing a container for the Node app separately.
> 
> Here's a thought though - we could add a bool parameters to the function like `ciMode` and if it's true use `npm ci` rather than `npm install`, then leave it to the consumer to dictate how that is set. It would mean that we don't have to code for how different CI environments report themselves, and gives more flexibility (you could even opt-in locally if desired).

Hi Aaron - the ciMode parameter to me is a greate idea - optin on the cloud, nothing to do for a dev environment.

To be honest i haven't found the "best" github actions build scripts yet for Aspire. Before Aspire (i.e. 2 months ago), i would build, test and publish in CI (publish the actual artifacts such as the containers and such) and then deploy by creating sublayers with appropriate config for specific environments which get push to the right place. Aspire changes that as i have a solution with everything inside yet i don't want to deploy everything everytime... still working on it...
